### ISSUE TITLE
`everyp`/`somef` operational equality bug

### ISSUE THREAD

**Issue by frenchy64** [frenchy64/fully-satisfies#6]
This line:
```clojure
(every? #(and (p1 %) (p2 %) (p3 %)) args)
```
should be
```clojure
(and (every? p1 args) (every? p2 args) (every? p3 args))
```

Basically the same problem as https://clojure.atlassian.net/browse/CLJ-2649 but in the rest arity.

**Comment by NoahTheDuke** [comment]
You think it should check all of `p1` before checking all of `p2`, etc?

**Comment by frenchy64** [comment]
Yes, I was surprised too. When I say "should", I'm referring to the operational equivalence with:

```clojure
(defn everyp [& ps]
  (fn [& args] (every? #(every? % args) ps)))
```

I think the "imperative" version you're talking about of would be:


```clojure
(defn everyp [& ps]
  (fn [& args] (every? (fn [x] (every? #(% x) ps) args)))
```

The problem is that the semantics are mixed. I think having both versions would be cool, but in different functions.

**Comment by frenchy64** [comment]
It's even worse than I thought. In these inner rest arities, `ep3` checks x, y, z against p1, then p2 then p3, but then the `every?` starts all over again for the rest of the args.

```clojure
       ([x y z & args] (boolean (and (ep3 x y z)
                                     (every? #(and (p1 %) (p2 %) (p3 %)) args))))))
```

**Comment by frenchy64** [comment]
I think it should be:

```
       ([x y z & args] (boolean (and (p1 x) (p1 y) (p1 z) (every? p1 args)
                                     (p2 x) (p2 y) (p2 z) (every? p2 args)
                                     (p3 x) (p3 y) (p3 z) (every? p3 args))))))

**Comment by frenchy64** [comment]
Same problem with `somef`. The arities that recur via `sf2`, `sf3`, `sfn` flip the order.
