### ISSUE TITLE
Failed test?

### ISSUE THREAD

**Issue by NoahTheDuke** [frenchy64/fully-satisfies#8]
Hey Ambrose! I tried the test suite under 1.11.1 and 1.12 alpha, and this test fails. I don't know anything about the issue or the fix, so maybe I did something wrong.

https://github.com/frenchy64/fully-satisfies/blob/aa0a873e67dd34078a2c58e638d7c5c73e1cd224/test/io/github/frenchy64/fully_satisfies/vector_overflow_test.clj#L28

**Comment by frenchy64** [comment]
Thanks @NoahTheDuke! This was due to changes in RT/intCast: https://github.com/clojure/clojure/commit/0cbf655d1
